### ISSUE TITLE
alt+enter 快捷键被拦截

### ISSUE THREAD

**Issue by tomatofrommars** [zhaoqin102/mybatis-support#2]
alt + enter 快捷键失效。
报错如下，找了我好久。。
```
2018-08-15 20:14:19,784 [  28527]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2018.2.1  Build #IU-182.3911.36 
2018-08-15 20:14:19,784 [  28527]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_152-release 
2018-08-15 20:14:19,784 [  28527]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
2018-08-15 20:14:19,784 [  28527]  ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2018-08-15 20:14:19,784 [  28527]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
2018-08-15 20:14:19,784 [  28527]  ERROR - llij.ide.plugins.PluginManager - Last Action: ShowIntentionActions 
2018-08-15 20:14:20,127 [  28870]  ERROR - .config.IntentionActionWrapper - org.muchu.mybatis.support.intention.GenerateStatementIntention PluginClassLoader[org.muchu.mybatis-support, 0.4] com.intellij.ide.plugins.cl.PluginClassLoader@7600c38c 
java.lang.ClassNotFoundException: org.muchu.mybatis.support.intention.GenerateStatementIntention PluginClassLoader[org.muchu.mybatis-support, 0.4] com.intellij.ide.plugins.cl.PluginClassLoader@7600c38c
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:47)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:47)
	at com.intellij.codeInsight.intention.IntentionActionBean.instantiate(IntentionActionBean.java:71)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.getDelegate(IntentionActionWrapper.java:95)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.getFamilyName(IntentionActionWrapper.java:57)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.getFullFamilyName(IntentionActionWrapper.java:85)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.getFamilyName(IntentionManagerSettings.java:108)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.isEnabled(IntentionManagerSettings.java:121)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.getAvailableIntentionActions(IntentionManagerImpl.java:283)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:314)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:280)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:274)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invoke(ShowIntentionActionsHandler.java:65)
	at com.intellij.codeInsight.intention.actions.ShowIntentionActionsAction.actionPerformed(ShowIntentionActionsAction.java:51)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:235)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:620)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:669)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:668)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:520)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:475)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2018-08-15 20:14:20,127 [  28870]  ERROR - .config.IntentionActionWrapper - IntelliJ IDEA 2018.2.1  Build #IU-182.3911.36 
2018-08-15 20:14:20,127 [  28870]  ERROR - .config.IntentionActionWrapper - JDK: 1.8.0_152-release 
2018-08-15 20:14:20,128 [  28871]  ERROR - .config.IntentionActionWrapper - VM: OpenJDK 64-Bit Server VM 
2018-08-15 20:14:20,128 [  28871]  ERROR - .config.IntentionActionWrapper - Vendor: JetBrains s.r.o 
2018-08-15 20:14:20,128 [  28871]  ERROR - .config.IntentionActionWrapper - OS: Mac OS X 
2018-08-15 20:14:20,128 [  28871]  ERROR - .config.IntentionActionWrapper - Last Action: ShowIntentionActions 
2018-08-15 20:14:20,128 [  28871]  ERROR - llij.ide.plugins.PluginManager - @NotNull method com/intellij/codeInsight/intention/impl/config/IntentionActionWrapper.getDelegate must not return null 
java.lang.IllegalStateException: @NotNull method com/intellij/codeInsight/intention/impl/config/IntentionActionWrapper.getDelegate must not return null
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.$$$reportNull$$$0(IntentionActionWrapper.java)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.getDelegate(IntentionActionWrapper.java:101)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.getFamilyName(IntentionActionWrapper.java:57)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.getFullFamilyName(IntentionActionWrapper.java:85)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.getFamilyName(IntentionManagerSettings.java:108)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.isEnabled(IntentionManagerSettings.java:121)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.getAvailableIntentionActions(IntentionManagerImpl.java:283)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:314)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:280)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:274)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invoke(ShowIntentionActionsHandler.java:65)
	at com.intellij.codeInsight.intention.actions.ShowIntentionActionsAction.actionPerformed(ShowIntentionActionsAction.java:51)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:235)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:620)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:669)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:668)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:520)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:475)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by zhaoqin102** [comment]
好的 我看下

**Comment by zhaoqin102** [comment]
我错了.. 都这么久了
